version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: booking_classroom_frontend
    networks:
      - mysibsau
      - default

networks:
  mysibsau:
    external: true
